# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos6"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v0.1.0/centos64-x86_64-20131030.box"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end

  config.vm.synced_folder "../../../", "/git"
  config.vm.synced_folder "../salt/roots/", "/srv/salt/"
  config.vm.provision :salt do |salt|
    salt.bootstrap_script = "../urllib-bootstrap-salt.sh"
    salt.minion_config = "../salt/minion"
    salt.run_highstate = false
  end
  config.vm.network :forwarded_port, guest: 22, host: 2201, id: "ssh", auto_correct: true
end
